"""initial schema: evidence-first ingestion data model

Revision ID: 94eea4d96250
Revises: 
Create Date: 2026-09-01 06:03:51.308698

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import modelkb.db.types  # noqa: F401 — JSONBCompat used by generated columns below


revision: str = '94eea4d96250'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('pdf', 'json', 'other', name='artifactkind', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('local_folder', 'sharepoint', 'manual', name='artifactorigin', native_enum=False, length=32), nullable=False),
    sa.Column('origin_ref', sa.String(length=1024), nullable=True),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact')),
    sa.UniqueConstraint('uid', name=op.f('uq_artifact_uid'))
    )
    op.create_table('claim',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_ref', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim')),
    sa.UniqueConstraint('ref', name=op.f('uq_claim_ref'))
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_model_ref'), ['model_ref'], unique=False)

    op.create_table('code_symbol',
    sa.Column('ref', sa.String(length=1024), nullable=False),
    sa.Column('git_tag', sa.String(length=255), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('repo_origin', sa.String(length=1024), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('qualname', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('imports', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('constant_value', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_symbol')),
    sa.UniqueConstraint('git_commit', 'path', 'qualname', name='uq_code_symbol_location'),
    sa.UniqueConstraint('ref', name=op.f('uq_code_symbol_ref'))
    )
    with op.batch_alter_table('code_symbol', schema=None) as batch_op:
        batch_op.create_index('ix_code_symbol_lookup', ['path', 'qualname'], unique=False)

    op.create_table('document',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('title_candidate', sa.String(length=1024), nullable=True),
    sa.Column('detected_model_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('ref', name=op.f('uq_document_ref'))
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_detected_model_ref'), ['detected_model_ref'], unique=False)

    op.create_table('model',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model')),
    sa.UniqueConstraint('ref', name=op.f('uq_model_ref'))
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_domain'), ['domain'], unique=False)

    op.create_table('review_state',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'needs_changes', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_state'))
    )
    with op.batch_alter_table('review_state', schema=None) as batch_op:
        batch_op.create_index('ix_review_state_entity', ['entity_type', 'entity_ref', 'is_current'], unique=False)

    op.create_table('schema_version',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('yaml_path', sa.String(length=1024), nullable=False),
    sa.Column('json_path', sa.String(length=1024), nullable=False),
    sa.Column('definition', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('proposal_run_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_run_id'], ['extraction_run.id'], name='fk_schema_version_proposal_run_id_extraction_run', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_version'))
    )
    op.create_table('artifact_version',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('archive_path', sa.String(length=1024), nullable=False),
    sa.Column('source_location', sa.String(length=1024), nullable=True),
    sa.Column('sharepoint_item_id', sa.String(length=255), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.Enum('pending', 'success', 'partial', 'failed', name='extractionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('extraction_warnings', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], name=op.f('fk_artifact_version_artifact_id_artifact'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_version')),
    sa.UniqueConstraint('sha256', name=op.f('uq_artifact_version_sha256'))
    )
    with op.batch_alter_table('artifact_version', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_version_artifact_current', ['artifact_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_version_artifact_id'), ['artifact_id'], unique=False)

    op.create_table('extraction_run',
    sa.Column('kind', sa.Enum('discovery', 'pdf_deterministic', 'schema_proposal', 'semantic_extraction', 'model_info_ingest', 'code_inventory', 'code_linking', 'artifact_generation', name='runkind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('params', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('stats', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('tool_versions', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_extraction_run_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_run'))
    )
    op.create_table('assumption',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('materiality', sa.String(length=32), nullable=True),
    sa.Column('extension', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_category', sa.Enum('explicit', 'inferred_from_text', 'ambiguous', name='reasoningcategory', native_enum=False, length=32), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_assumption_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_assumption_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumption'))
    )
    with op.batch_alter_table('assumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumption_model_ref'), ['model_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_assumption_ref'), ['ref'], unique=False)
        batch_op.create_index('ix_assumption_ref_current', ['ref', 'is_current'], unique=False)

    op.create_table('change_event',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_change_event_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_event'))
    )
    with op.batch_alter_table('change_event', schema=None) as batch_op:
        batch_op.create_index('ix_change_event_entity', ['entity_ref', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_event_kind'), ['kind'], unique=False)

    op.create_table('claim_version',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_category', sa.Enum('explicit', 'inferred_from_text', 'ambiguous', name='reasoningcategory', native_enum=False, length=32), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('fk_claim_version_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_claim_version_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_claim_version_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_version'))
    )
    with op.batch_alter_table('claim_version', schema=None) as batch_op:
        batch_op.create_index('ix_claim_version_claim_current', ['claim_id', 'is_current'], unique=False)

    op.create_table('coefficient',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('equation_ref', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('extension', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_category', sa.Enum('explicit', 'inferred_from_text', 'ambiguous', name='reasoningcategory', native_enum=False, length=32), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_coefficient_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_coefficient_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coefficient'))
    )
    with op.batch_alter_table('coefficient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coefficient_model_ref'), ['model_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_coefficient_ref'), ['ref'], unique=False)
        batch_op.create_index('ix_coefficient_ref_current', ['ref', 'is_current'], unique=False)

    op.create_table('document_version',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=True),
    sa.Column('doc_date', sa.String(length=32), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.id'], name=op.f('fk_document_version_artifact_version_id_artifact_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_version_document_id_document'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version')),
    sa.UniqueConstraint('document_id', 'artifact_version_id', name='uq_document_version_artifact'),
    sa.UniqueConstraint('ref', name=op.f('uq_document_version_ref'))
    )
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_version_document_id'), ['document_id'], unique=False)

    op.create_table('equation',
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=True),
    sa.Column('variable_refs', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('extension', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_category', sa.Enum('explicit', 'inferred_from_text', 'ambiguous', name='reasoningcategory', native_enum=False, length=32), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_equation_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_equation_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equation'))
    )
    with op.batch_alter_table('equation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equation_model_ref'), ['model_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_equation_ref'), ['ref'], unique=False)
        batch_op.create_index('ix_equation_ref_current', ['ref', 'is_current'], unique=False)

    op.create_table('llm_interaction',
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('success', 'validation_failed', 'error', name='llminteractionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('validation_errors', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('request_payload', modelkb.db.types.JSONBCompat(), nullable=True),
    sa.Column('response_payload', modelkb.db.types.JSONBCompat(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_llm_interaction_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_interaction'))
    )
    with op.batch_alter_table('llm_interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_interaction_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_interaction_purpose'), ['purpose'], unique=False)

    op.create_table('model_info_snapshot',
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('parsed', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('connection_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.id'], name=op.f('fk_model_info_snapshot_artifact_version_id_artifact_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_model_info_snapshot_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_info_snapshot'))
    )
    op.create_table('relationship',
    sa.Column('subject_ref', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_ref', sa.String(length=255), nullable=False),
    sa.Column('asserted_by', sa.Enum('pdf', 'model_info_json', 'human', name='assertedby', native_enum=False, length=32), nullable=False),
    sa.Column('source_precedence', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'active', 'superseded', 'disputed', name='relationshipstatus', native_enum=False, length=32), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current_view', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('extension', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_relationship_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_relationship_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship'))
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index('ix_relationship_forward', ['subject_ref', 'predicate', 'status'], unique=False)
        batch_op.create_index('ix_relationship_reverse', ['object_ref', 'predicate', 'status'], unique=False)

    op.create_table('variable',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('symbol', sa.String(length=128), nullable=True),
    sa.Column('dtype', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extension', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_category', sa.Enum('explicit', 'inferred_from_text', 'ambiguous', name='reasoningcategory', native_enum=False, length=32), nullable=True),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version_id', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_variable_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_version.id'], name=op.f('fk_variable_schema_version_id_schema_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variable'))
    )
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variable_model_ref'), ['model_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_variable_ref'), ['ref'], unique=False)
        batch_op.create_index('ix_variable_ref_current', ['ref', 'is_current'], unique=False)

    op.create_table('code_reference',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_path', sa.String(length=1024), nullable=True),
    sa.Column('symbol_candidate', sa.String(length=1024), nullable=True),
    sa.Column('pattern_name', sa.String(length=128), nullable=True),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('git_tag', sa.String(length=255), nullable=True),
    sa.Column('resolution_status', sa.Enum('unresolved', 'resolved', 'ambiguous', 'obsolete', name='resolutionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('resolved_symbol_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_symbol_ids', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_code_reference_document_version_id_document_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], name=op.f('fk_code_reference_extraction_run_id_extraction_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_symbol_id'], ['code_symbol.id'], name=op.f('fk_code_reference_resolved_symbol_id_code_symbol'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_reference'))
    )
    with op.batch_alter_table('code_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_reference_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index('ix_code_reference_status', ['resolution_status', 'is_current'], unique=False)

    op.create_table('model_version',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('documented_by_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['documented_by_id'], ['document_version.id'], name=op.f('fk_model_version_documented_by_id_document_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_version_model_id_model'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_version')),
    sa.UniqueConstraint('ref', name=op.f('uq_model_version_ref'))
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index('ix_model_version_model_current', ['model_id', 'is_current'], unique=False)

    op.create_table('page',
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_warnings', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_page_document_version_id_document_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page')),
    sa.UniqueConstraint('document_version_id', 'page_number', name='uq_page_docver_number')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_document_version_id'), ['document_version_id'], unique=False)

    op.create_table('section',
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('heading_text', sa.String(length=1024), nullable=False),
    sa.Column('heading_path', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('detection', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_section_document_version_id_document_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['section.id'], name=op.f('fk_section_parent_id_section'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section'))
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index('ix_section_docver_order', ['document_version_id', 'order_index'], unique=False)

    op.create_table('source_locator',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('artifact_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('section_path', modelkb.db.types.JSONBCompat(), nullable=True),
    sa.Column('kind', sa.Enum('text_span', 'table', 'equation', 'figure', 'document', 'metadata', name='locatorkind', native_enum=False, length=32), nullable=False),
    sa.Column('bounding_box', modelkb.db.types.JSONBCompat(), nullable=True),
    sa.Column('text_start', sa.Integer(), nullable=True),
    sa.Column('text_end', sa.Integer(), nullable=True),
    sa.Column('table_label', sa.String(length=128), nullable=True),
    sa.Column('equation_label', sa.String(length=128), nullable=True),
    sa.Column('extracted_text_hash', sa.String(length=64), nullable=True),
    sa.Column('extraction_limitations', modelkb.db.types.JSONBCompat(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_version.id'], name=op.f('fk_source_locator_artifact_version_id_artifact_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_source_locator_document_version_id_document_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=op.f('fk_source_locator_section_id_section'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_locator'))
    )
    with op.batch_alter_table('source_locator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_locator_artifact_version_id'), ['artifact_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_locator_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index('ix_source_locator_page', ['artifact_version_id', 'page'], unique=False)

    op.create_table('assumption_evidence',
    sa.Column('assumption_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumption.id'], name=op.f('fk_assumption_evidence_assumption_id_assumption'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_assumption_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assumption_id', 'source_locator_id', name=op.f('pk_assumption_evidence'))
    )
    op.create_table('claim_version_evidence',
    sa.Column('claim_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['claim_version_id'], ['claim_version.id'], name=op.f('fk_claim_version_evidence_claim_version_id_claim_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_claim_version_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_version_id', 'source_locator_id', name=op.f('pk_claim_version_evidence'))
    )
    op.create_table('code_reference_evidence',
    sa.Column('code_reference_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['code_reference_id'], ['code_reference.id'], name=op.f('fk_code_reference_evidence_code_reference_id_code_reference'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_code_reference_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_reference_id', 'source_locator_id', name=op.f('pk_code_reference_evidence'))
    )
    op.create_table('coefficient_evidence',
    sa.Column('coefficient_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['coefficient_id'], ['coefficient.id'], name=op.f('fk_coefficient_evidence_coefficient_id_coefficient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_coefficient_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coefficient_id', 'source_locator_id', name=op.f('pk_coefficient_evidence'))
    )
    op.create_table('equation_evidence',
    sa.Column('equation_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['equation_id'], ['equation.id'], name=op.f('fk_equation_evidence_equation_id_equation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_equation_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equation_id', 'source_locator_id', name=op.f('pk_equation_evidence'))
    )
    op.create_table('relationship_evidence',
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], name=op.f('fk_relationship_evidence_relationship_id_relationship'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_relationship_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', 'source_locator_id', name=op.f('pk_relationship_evidence'))
    )
    op.create_table('variable_evidence',
    sa.Column('variable_id', sa.Uuid(), nullable=False),
    sa.Column('source_locator_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], name=op.f('fk_variable_evidence_source_locator_id_source_locator'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], name=op.f('fk_variable_evidence_variable_id_variable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variable_id', 'source_locator_id', name=op.f('pk_variable_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable_evidence')
    op.drop_table('relationship_evidence')
    op.drop_table('equation_evidence')
    op.drop_table('coefficient_evidence')
    op.drop_table('code_reference_evidence')
    op.drop_table('claim_version_evidence')
    op.drop_table('assumption_evidence')
    with op.batch_alter_table('source_locator', schema=None) as batch_op:
        batch_op.drop_index('ix_source_locator_page')
        batch_op.drop_index(batch_op.f('ix_source_locator_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_source_locator_artifact_version_id'))

    op.drop_table('source_locator')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index('ix_section_docver_order')
        batch_op.drop_index(batch_op.f('ix_section_document_version_id'))

    op.drop_table('section')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_document_version_id'))

    op.drop_table('page')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index('ix_model_version_model_current')

    op.drop_table('model_version')
    with op.batch_alter_table('code_reference', schema=None) as batch_op:
        batch_op.drop_index('ix_code_reference_status')
        batch_op.drop_index(batch_op.f('ix_code_reference_document_version_id'))

    op.drop_table('code_reference')
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.drop_index('ix_variable_ref_current')
        batch_op.drop_index(batch_op.f('ix_variable_ref'))
        batch_op.drop_index(batch_op.f('ix_variable_model_ref'))

    op.drop_table('variable')
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index('ix_relationship_reverse')
        batch_op.drop_index('ix_relationship_forward')

    op.drop_table('relationship')
    op.drop_table('model_info_snapshot')
    with op.batch_alter_table('llm_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_interaction_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_interaction_extraction_run_id'))

    op.drop_table('llm_interaction')
    with op.batch_alter_table('equation', schema=None) as batch_op:
        batch_op.drop_index('ix_equation_ref_current')
        batch_op.drop_index(batch_op.f('ix_equation_ref'))
        batch_op.drop_index(batch_op.f('ix_equation_model_ref'))

    op.drop_table('equation')
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_version_document_id'))

    op.drop_table('document_version')
    with op.batch_alter_table('coefficient', schema=None) as batch_op:
        batch_op.drop_index('ix_coefficient_ref_current')
        batch_op.drop_index(batch_op.f('ix_coefficient_ref'))
        batch_op.drop_index(batch_op.f('ix_coefficient_model_ref'))

    op.drop_table('coefficient')
    with op.batch_alter_table('claim_version', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_version_claim_current')

    op.drop_table('claim_version')
    with op.batch_alter_table('change_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_event_kind'))
        batch_op.drop_index('ix_change_event_entity')

    op.drop_table('change_event')
    with op.batch_alter_table('assumption', schema=None) as batch_op:
        batch_op.drop_index('ix_assumption_ref_current')
        batch_op.drop_index(batch_op.f('ix_assumption_ref'))
        batch_op.drop_index(batch_op.f('ix_assumption_model_ref'))

    op.drop_table('assumption')
    op.drop_table('extraction_run')
    with op.batch_alter_table('artifact_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_version_artifact_id'))
        batch_op.drop_index('ix_artifact_version_artifact_current')

    op.drop_table('artifact_version')
    op.drop_table('schema_version')
    with op.batch_alter_table('review_state', schema=None) as batch_op:
        batch_op.drop_index('ix_review_state_entity')

    op.drop_table('review_state')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_domain'))

    op.drop_table('model')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_detected_model_ref'))

    op.drop_table('document')
    with op.batch_alter_table('code_symbol', schema=None) as batch_op:
        batch_op.drop_index('ix_code_symbol_lookup')

    op.drop_table('code_symbol')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_model_ref'))

    op.drop_table('claim')
    op.drop_table('artifact')
    # ### end Alembic commands ###
